version: '3.6'
networks:
  web-scientist:
    driver: bridge
services:
  web-scientist:
    build: .
    image: "docker.sprinteins.com/users/trusz/web-scientist:v1.0.0"
    
  web-scientist-dev:
    build: 
        context: .
        dockerfile: dev.Dockerfile
    ports:
      - "1234:1234"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    command: ["sh","-c","cd /app/src && realize start"]
    networks:
      - web-scientist